language: android
android:
  components:
  - android-23
  - build-tools-23.0.1
  - platform-tools
  - extra-google-m2repository
  - extra-android-m2repository
  
  # Additional components		
  - extra
  
before_install:		
- chmod +x gradlew

sudo: false

before_script:
- GRADLE_OPTS="-Xms40m -Xmx3g -XX:MaxPermSize=3g"
branches:
  only:
  - master
