language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-19.1.0

    # The SDK version used to compile your project
    - android-19
    
before_install:
 - chmod +x gradlew
 
jdk:
  - oraclejdk7

script:
  - ./gradlew clean build

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
