language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - android-22
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-19
    
    # Additional components
    - extra

before_install:
 - chmod +x gradlew
 
jdk:
  - oraclejdk7

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
